### ISSUE TITLE
Unable to reach platform.

### ISSUE THREAD

**Issue by ednerd** [contentsync/SketchContentSync.sketchplugin#22]
The ContentSync.app shows that it is unable to reach platform and thus syncing is not possible.
<img width="410" alt="screen shot 2017-01-04 at 4 18 03 pm" src="https://cloud.githubusercontent.com/assets/1708548/21664111/64c78676-d299-11e6-8b9a-0000e12e1a00.png">

**Comment by dbrody** [comment]
@ednerd, sorry to hear. That error indicates that the OSX Application is having trouble getting the data for your project / version. I can think of a few possibilities:

+ You are not signed in on the OSX Application, it may help to log out and then log back in
+ The project / version you are using are invalid, somehow an incorrect value was saved or something on your document changed. It may help to retry resetting the project and version you are syncing.

If those don't help, maybe post a bit more information about your usage and we can try to debug further.

**Comment by ednerd** [comment]
Thanks for the reply, @dbrody. 

I did try logging out and back in of the OSX Application and got the same error. 
I'm not sure how I would retry resetting the project and version as it the OSX Application doesn't give me any way to select a project or version. It just goes from Syncing to Unable to reach platform.
Also, how does one delete a project?

**Comment by dbrody** [comment]
@ednerd, thanks for the follow up.

There is now a new version (0.6.13) of the OSX App. When you open the app, it should automatically prompt you to check for and install the updates.

This new version will display an error code with a bit more details. It will also include a button to clear settings saved within the app.

Let me know what the error that shows up is now, and if using the clear settings button helps.

**Comment by ednerd** [comment]
Thanks, @dbrody.

I was able to update the OSX App to 0.6.13 and I did the sign out/in path which cleared settings as well. The unable to reach platform error was still there but, the error code was just 0 with no further details.

I got the prompt to select a project but, I was not able to see any versions in my project. If I selected your sample spreadsheet, versions were available. Maybe my spreadsheet is formatted incorrectly and it's choking on something. It's hard to tell. I'll try recreating my spreadsheet. 

Is there a way that I can manage the projects listed in my contentsync.io dashboard? I'd like to delete duplicates/mistakes.

Thanks for your work.

**Comment by dbrody** [comment]
@ednerd Yes, there will be a large update coming soon to allow for managing projects as well as creating organizations and sharing projects.

In diving a bit deeper, it looks like the issue is that your project sync requests are timing out. It seems as if your requests are large and seem to time out our server. I filed an issue for that to see if we can break the large request into smaller parts but it may take some time to get that implemented.

Given that issue, can you tell me any details on the document you are trying to sync? How many versions, how many keys, is some of the content large, etc?

Thanks,
David

**Comment by dbrody** [comment]
@ednerd 

After diving a bit deeper, it looks like our server was being a bit overloaded with more traffic than we thought. We've upgraded the servers and put a few optimizations in place and it looks like it should work now.

Let me know how it goes, hopefully your issue should be resolved now.

**Comment by ednerd** [comment]
Sync requests do seem to take a while but, I'm not getting the Platform Unreachable error anymore. But, versions are still not available from my document. It's a sizeable sheet with only 2 versions but around 320 keys but the content is only a few words for each key.

**Comment by dbrody** [comment]
@ednerd, there is now another update to 0.6.14.

This should help a lot with the time of syncs. It introduces a couple optimizations on the data transfer so that not all data is transferred every sync.

Try to do your syncs again with this new version and let me know how it goes.

**Comment by dbrody** [comment]
@ednerd we dove a bit further in and it appears to have been an issue with the GoogleAPI request response size. We see that with a document of 300 keys, Google's API response was in the 80MB size which was causing all sorts of issues. We optimized that request and now it should be on the order of 2KB response. This should drastically improve speed and response time.

This is available in 0.6.16.

We are still looking into more ways to continue improving the performance, scalability and experience. As always, post any issues, comments, questions, etc here on Github or send an email to support@contentsync.io .  Thank you for using ContentSync!
